<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>Warden</AssemblyName>
    <RootNamespace>Warden</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWpf>true</UseWpf>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <!-- Paketlerin onlarca dildeki uydu kaynak klasörlerini çıktıya kopyalama (uygulama yalnızca TR/EN) -->
    <SatelliteResourceLanguages>en;tr</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\icon.ico" />
    <Resource Include="Assets\icon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.3" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="NvAPIWrapper.Net" Version="0.8.1.101" />
  </ItemGroup>

</Project>
