using System.Collections.Generic;

namespace Warden
{
    public static class Loc
    {
        public static string CurrentLang { get; set; } = "TR";

        private static readonly Dictionary<string, Dictionary<string, string>> Strings = new()
        {
            {
                "EN", new Dictionary<string, string>
                {
                    // General / Shell
                    { "Title",                  "Warden" },
                    { "Online",                 "ONLINE" },
                    { "Settings",               "Settings" },
                    { "SettingsHeader",         "Settings" },
                    { "SettingsDesc",           "Turn on only what you use. Changes apply right away." },
                    { "GoToDevicesPage",        "Open Audio page →" },
                    { "DeviceSettingsHint",     "Devices to keep disabled are chosen on the Audio page." },
                    { "GoToGpuPage",            "Open GPU page →" },
                    { "GpuSettingsHint",        "The clock limit and the Afterburner profile are set on the GPU page." },
                    { "IntervalSeconds",        "Every {0} s" },
                    { "AutoSaveHint",           "Changes are saved automatically ✓" },
                    { "GeneralSection",         "GENERAL" },
                    { "StartWithWin",           "Start with Windows" },
                    { "StartWithWinDesc",       "Automatically launches minimized in system tray on system boot." },
                    { "StartupInsecureTitle",   "Start with Windows disabled" },
                    { "NavOverview",             "Dashboard" },
                    { "NavShortOverview",        "Panel" },
                    { "NavShortSonar",           "Sonar" },
                    { "NavShortAudio",           "Audio" },
                    { "NavShortGpu",             "GPU" },
                    { "NavShortSensors",         "Sensors" },
                    { "NavShortStatus",          "Status" },
                    { "NavShortSettings",        "Settings" },
                    { "OvTitle",                 "Dashboard" },
                    { "OvDesc",                  "Game and system status at a glance" },
                    { "OvScan",                  "Scan games" },
                    { "OvRecordStart",           "● RECORD" },
                    { "OvRecordStop",            "■ STOP" },
                    { "OvInGame",                "IN GAME" },
                    { "OvDesktop",               "DESKTOP" },
                    { "OvDesktopHint",           "A game with a rule will show up here when it is running" },
                    { "OvSession",               "session" },
                    { "OvLoad",                  "Load {0}" },
                    { "OvClock",                 "Clock {0}" },
                    { "OvPower",                 "Power {0}" },
                    { "OvGraph",                 "LAST 60 SECONDS · TEMPERATURE" },
                    { "OvTileRam",               "Memory" },
                    { "OvTileHotSpot",           "GPU hot spot" },
                    { "OvTileFan",               "Fastest fan" },
                    { "OvTileCpuPower",          "CPU power" },
                    { "OvChipRecord",            "Recording" },
                    { "OvChipUpdate",            "Version" },
                    { "OvConnected",             "CONNECTED" },
                    { "OvDisconnected",          "NOT CONNECTED" },
                    { "OvReady",                 "READY" },
                    { "OvMissing",               "MISSING" },
                    { "OvOff",                   "OFF" },
                    { "OvRecording",             "RECORDING" },
                    { "OvIdle",                  "IDLE" },
                    { "OvUpdateAvailable",       "{0} AVAILABLE" },
                    { "SonarConnectedAt",        "Sonar connected: {0}" },
                    { "SonarWidgetHint",         "Click for system status" },
                    { "NavStatus",               "System Status" },
                    { "GpuNotFound",             "No GPU sensor found" },
                    { "GpuDetecting",            "Detecting GPU..." },
                    { "TempAlarm",               "⚠ {0} temperature is {1}°C (limit {2}°C)" },
                    { "TempAlarmTitle",          "Temperature alarm" },
                    { "TempAlarmDesc",           "Notifies you when a temperature stays above its limit for 10 seconds (at most every 10 minutes)." },
                    { "CpuTempLimit",            "CPU limit (°C)" },
                    { "GpuTempLimit",            "GPU limit (°C)" },
                    { "RecordAuto",              "Record automatically while a game with a rule is running" },
                    { "RecordOpenFolder",        "📁 Recordings" },
                    { "RecordStart",             "⏺ Start recording" },
                    { "RecordStop",              "⏹ Stop" },
                    { "RecordIdle",              "Not recording" },
                    { "RecordActive",            "Recording: {0} ({1}) → {2}" },
                    { "RecordKindAuto",          "automatic" },
                    { "RecordKindManual",        "manual" },
                    { "RecordManualLabel",       "manual" },
                    { "StatusHeader",            "System Status" },
                    { "StatusDesc",              "Programs and drivers Warden relies on. Features whose requirement is missing will not work." },
                    { "StatusRecheck",           "Check again" },
                    { "StatusChecking",          "Checking..." },
                    { "StatusDownload",          "Download" },
                    { "StatusAdmin",             "Administrator rights" },
                    { "StatusAdminOk",           "Warden is running elevated (needed for sensors and audio devices)." },
                    { "StatusAdminMissing",      "Not elevated: sensors and audio device control will not work." },
                    { "StatusInstall",           "Install location" },
                    { "StatusInstallOk",         "Protected folder: {0}. \"Start with Windows\" can be used." },
                    { "StatusInstallInsecure",   "The folder can be modified by standard users, so \"Start with Windows\" stays off. Install with the setup. ({0})" },
                    { "StatusGgOk",              "Installed." },
                    { "StatusGgMissing",         "Not installed: automatic Sonar EQ switching will not work." },
                    { "StatusSonarOk",           "Running at {0}." },
                    { "StatusSonarMissing",      "Not reachable: open SteelSeries GG and make sure Sonar is enabled." },
                    { "StatusAfterburnerMissing", "Not found: the automatic GPU profile will not work." },
                    { "StatusPawnIoOk",          "Installed: CPU sensors are available." },
                    { "StatusPawnIoMissing",     "Not installed: CPU temperature, clock and power may stay empty (winget install namazso.PawnIO)." },
                    { "StatusGpu",               "Graphics card" },
                    { "StatusGpuMissing",        "No GPU sensor found. The GPU page and the GPU temperature alarm will be empty." },
                    { "StatusUpdate",            "Updates" },
                    { "UpdatesSection",          "UPDATES" },
                    { "UpdateAutoCheck",         "Check for updates automatically" },
                    { "UpdateAutoCheckDesc",     "Checks GitHub Releases at startup and every 6 hours." },
                    { "UpdateCurrentVersion",    "Installed version: {0}" },
                    { "BtnCheckUpdates",         "Check now" },
                    { "BtnInstallUpdate",        "Install {0}" },
                    { "UpdateChecking",          "Checking for updates..." },
                    { "UpdateUpToDate",          "You're on the latest version." },
                    { "UpdateAvailable",         "New version available: {0}" },
                    { "UpdateUnavailable",       "Couldn't get release info (is the repository private?)." },
                    { "UpdateError",             "Update check failed: {0}" },
                    { "UpdateDownloading",       "Downloading... {0}%" },
                    { "UpdateInstalling",        "Installing, Warden will restart in a few seconds..." },
                    { "UpdateFailed",            "Update failed: {0}" },
                    { "UpdateHashMismatch",      "the downloaded file could not be verified (SHA256 mismatch). Nothing was installed." },
                    { "UpdateCancelled",         "The update was not completed; Warden keeps running." },
                    { "UpdateBalloon",           "Warden {0} is available. Click to install." },
                    { "UpdateConfirm",           "Install Warden {0} now?\n\nWarden will close and restart in a few seconds. Your settings are kept." },
                    { "UpdateConfirmTitle",      "Warden update" },
                    { "TrayInstallUpdate",       "Install update ({0})" },
                    { "RuleExists",             "{0} already has a rule. Change that rule's preset instead." },
                    { "PawnIoMissing",          "PawnIO driver is not installed, so CPU temperature, clock and power sensors may stay empty. Install it with \"winget install namazso.PawnIO\" or from" },
                    { "StartupInsecureBody",    "Warden starts at logon with administrator rights, but its folder can be modified by standard users:\n\n{0}\n\nAny program running as you could replace Warden.exe or one of its DLLs and gain administrator rights at the next logon. \"Start with Windows\" has been turned off.\n\nTo enable it, publish Warden into a protected folder (e.g. C:\\Program Files\\Warden) from an elevated terminal:\ndotnet publish -c Release -o \"C:\\Program Files\\Warden\"\n\nDetail: {1}" },
                    { "Language",               "Language / Dil" },
                    { "ScanInterval",           "Game check frequency" },
                    { "ScanIntervalDesc",       "How often Warden checks which game is in focus. Shorter switches faster, longer uses less CPU." },
                    { "BtnSave",                "Save" },
                    { "SaveSuccess",            "Settings saved successfully!" },
                    { "SavedSuccess",           "Saved ✔" },
                    { "Connecting",             "Connecting..." },
                    { "Connected",              "Connected" },
                    { "ConnFailed",             "Connection Failed" },
                    { "Active",                 "Active" },
                    { "Desktop",                "Desktop" },
                    { "Info",                   "Info" },
                    { "Warning",                "Warning" },
                    { "Error",                  "Error" },

                    // Window Chrome Tooltips
                    { "ToolTipMinimize",        "Minimize" },
                    { "ToolTipMaximize",        "Maximize" },
                    { "ToolTipClose",           "Close (Runs in background tray)" },

                    // Navigation Tooltips
                    { "NavHome",                "Sonar Profiles" },
                    { "NavDeviceManager",       "Audio Device Manager" },
                    { "NavGpuMonitor",          "GPU Monitor" },
                    { "NavTelemetry",           "Hardware Monitor" },
                    { "NavSettings",            "Settings" },

                    // Page 1: Sonar Profiles & Rules
                    { "RulesHeader",            "Auto Switch Profiles" },
                    { "RulesDesc",              "Automatically switches SteelSeries Sonar profiles based on active games and apps." },
                    { "DefaultEQ",              "Default Profile:" },
                    { "DefaultEQDesc",          "Used when no custom rule matches or while on the desktop." },
                    { "PerAppConfig",           "APPLICATION / GAME" },
                    { "TargetSonarConfig",      "TARGET SONAR PROFILE" },
                    { "BtnScan",                "Scan Installed Games" },
                    { "BtnClear",               "Reset" },
                    { "ClearScannedGames",      "Clear Scanned Games" },
                    { "ClearScannedGamesDesc",  "Resets the list of scanned background games." },
                    { "ClearedSuccess",         "Scanned games list has been reset." },
                    { "ClearedSuccessTitle",    "Reset Complete" },
                    { "ManualAdd",              "Add Manually:" },
                    { "ManualAddDesc",          "If a game was not found in scan, enter its executable name manually." },
                    { "ManualExe",              "Executable Name" },
                    { "ManualName",             "Display Name (Optional)" },
                    { "ManualBrowse",           "Browse" },
                    { "BtnAddManual",           "Add" },
                    { "BtnAddRule",             "Add Game" },
                    { "BtnDeleteRule",          "Remove" },
                    { "ManualSuccess",          "Game added successfully!" },
                    { "ScanDone",               "{0} new games found" },
                    { "ScanNone",               "No new games found" },
                    { "ScanMatched",            "{0} GG profiles assigned" },
                    { "ScanRemoved",            "{0} uninstalled games removed" },
                    { "ScanBusy",               "A scan is already running" },
                    { "AutoScanAdded",          "New games: {0}" },
                    { "AutoScanAssigned",       "GG profile assigned: {0}" },
                    { "AutoScanRemoved",        "Uninstalled: {0}" },
                    { "AutoScan",               "Scan installed games on startup" },
                    { "AutoScanDesc",           "Finds new and uninstalled games and notifies you when something changed." },
                    { "AutoAssign",             "Assign GG game profiles automatically" },
                    { "AutoAssignDesc",         "Games with a dedicated SteelSeries GG profile get that profile. Existing rules are kept." },
                    { "ModulesSection",         "MODULES" },
                    { "ModuleSonar",            "Sonar profile switching" },
                    { "ModuleSonarDesc",        "When a game is in focus, switches the SteelSeries Sonar audio profile to the one set for it and goes back to the default profile when the game closes. When off, Warden does not talk to SteelSeries GG at all; game tracking (Panel, automatic recording) keeps working." },
                    { "ModuleAudioDevices",     "Audio device enforcer" },
                    { "ModuleAudioDevicesDesc", "Keeps the selected audio devices (for example unused virtual or ghost devices) disabled. If Windows or GG turns them back on, they are disabled again within 30 seconds." },
                    { "ModuleHardware",         "Hardware monitoring" },
                    { "ModuleHardwareDesc",     "Reads CPU and GPU temperature, clock speed, power and fans. The Sensors page, Panel gauges, temperature alarm and CSV recording use it. When off, the sensor driver is never loaded; turn it off if a game's anti-cheat has problems with it." },
                    { "ModuleGpuProfile",       "GPU / Afterburner profile" },
                    { "ModuleGpuProfileDesc",   "When the GPU clock goes over the set limit, applies the chosen MSI Afterburner profile (for example a power-limited one). It reads the clock from the sensors, so hardware monitoring must be on." },
                    { "ModuleOffTitle",         "This module is off" },
                    { "ModuleOffDesc",          "It does not run in the background. Turn it on to use this page." },
                    { "ModuleGpuNeedsHardware", "The GPU profile reads the clock from the sensors, so hardware monitoring is turned on with it." },
                    { "ModuleEnable",           "Turn module on" },
                    { "SonarModuleOff",         "Sonar module is off" },
                    { "StatusModuleOff",        "Module is off" },
                    { "SessionSummaryTitle",    "{0} · {1}" },
                    { "SessionSummaryMaxTemp",  "{0} max {1} °C" },
                    { "DurationHoursMinutes",   "{0} h {1} min" },
                    { "DurationMinutes",        "{0} min" },
                    { "SessionSummary",         "Show a summary when a game closes" },
                    { "SessionSummaryDesc",     "A notification with the play time and the highest CPU and GPU temperature." },
                    { "HistoryColGpuMax",       "GPU MAX" },
                    { "HistoryColCpuMax",       "CPU MAX" },
                    { "HistoryColDuration",     "DURATION" },
                    { "HistoryColDate",         "DATE" },
                    { "HistoryColGpu",          "GPU AVG / MAX" },
                    { "HistoryColCpu",          "CPU AVG / MAX" },
                    { "HistoryColLastPlayed",   "LAST PLAYED" },
                    { "HistoryColSessions",     "SESSIONS" },
                    { "HistoryColTotal",        "TOTAL" },
                    { "HistoryColGame",         "GAME" },
                    { "HistorySessionsSection", "RECENT SESSIONS" },
                    { "Seconds",                "{0} s" },
                    { "BenchmarkWarmupDesc",    "Dropped from the start of each run (loading, shader compilation, boost ramp-up)." },
                    { "BenchmarkWarmup",        "Warm-up" },
                    { "BenchmarkHotkeyTaken",   "{0} is already used by another application; pick another key." },
                    { "BenchmarkHotkeyDesc",    "Starts / stops a recording from inside the game." },
                    { "BenchmarkHotkey",        "Recording hotkey" },
                    { "ModuleBenchmarkDesc",    "You change the settings (e.g. Afterburner profiles); Warden records FPS, frame times, temperature, power and clocks every second and works out average FPS, 1% low and FPS per watt. FPS needs RTSS (comes with Afterburner). When off, no hotkey is registered." },
                    { "ModuleBenchmark",        "Benchmark / Compare" },
                    { "BenchmarkTooShort",      "Shorter than the warm-up time, summary is incomplete." },
                    { "BenchmarkStoppedFps",    "Avg {0} FPS · 1% low {1}" },
                    { "BenchmarkStopped",       "Benchmark recording stopped: {0} · {1}" },
                    { "BenchmarkStarted",       "Benchmark recording started: {0}\nPress {1} to stop" },
                    { "BenchmarkAutoLabel",     "Run {0}" },
                    { "BenchmarkDeleteConfirm", "Delete the run \"{0}\"?" },
                    { "BenchmarkDelete",        "Delete run" },
                    { "BenchmarkRenameTip",     "Click to rename" },
                    { "BenchmarkRunShort",      "Shorter than the warm-up time; no summary." },
                    { "BenchmarkRunEfficiency", "{0} FPS/W ({1})" },
                    { "BenchmarkRunDevice",     "{0} avg {1} MHz ({2}–{3}) · {4} / {5} °C (avg / p95) · {6} W · {7}% load" },
                    { "BenchmarkRunFps",        "Avg {0} FPS · 1% low {1}" },
                    { "BenchmarkNoRuns",        "No runs yet." },
                    { "EffTotal",               "Total" },
                    { "EffCpu",                 "CPU" },
                    { "EffGpu",                 "GPU" },
                    { "BenchmarkEfficiency",    "FPS per watt:" },
                    { "BenchmarkRunsSection",   "RUNS" },
                    { "ChartCpuClock",          "CPU clock" },
                    { "ChartGpuClock",          "GPU clock" },
                    { "ChartTotalPower",        "Total power" },
                    { "ChartCpuPower",          "CPU power" },
                    { "ChartGpuPower",          "GPU power" },
                    { "ChartCpuTemp",           "CPU temperature" },
                    { "ChartGpuTemp",           "GPU temperature" },
                    { "ChartFps",               "FPS" },
                    { "CmpCpuLoad",             "CPU load (%)" },
                    { "CmpGpuLoad",             "GPU load (%)" },
                    { "CmpTotalPower",          "Total power (W)" },
                    { "CmpCpuPower",            "CPU power (W)" },
                    { "CmpGpuPower",            "GPU power (W)" },
                    { "CmpCpuTempP95",          "CPU temp p95 (°C)" },
                    { "CmpCpuTemp",             "CPU temp avg (°C)" },
                    { "CmpGpuTempP95",          "GPU temp p95 (°C)" },
                    { "CmpGpuTemp",             "GPU temp avg (°C)" },
                    { "CmpCpuClock",            "CPU clock avg (MHz)" },
                    { "CmpCpuClockMin",         "CPU clock min (MHz)" },
                    { "CmpCpuClockMax",         "CPU clock max (MHz)" },
                    { "CmpGpuClock",            "GPU clock avg (MHz)" },
                    { "CmpGpuClockMin",         "GPU clock min (MHz)" },
                    { "CmpGpuClockMax",         "GPU clock max (MHz)" },
                    { "CmpFpsPerWatt",          "FPS per watt ({0})" },
                    { "CmpLow1Fps",             "1% low FPS" },
                    { "CmpAvgFps",              "Average FPS" },
                    { "CmpMetric",              "Metric" },
                    { "CsvSamplesSuffix",       "-samples" },
                    { "BenchmarkChartNoData",   "No data for this metric." },
                    { "BenchmarkBaseline",      "baseline" },
                    { "BenchmarkRunsCount",     "{0} run(s)" },
                    { "BenchmarkSelectTip",     "Add to comparison" },
                    { "BenchmarkCompareMax",    "At most {0} groups are compared; the rest are not shown." },
                    { "BenchmarkCompareBaseline", "Baseline: {0}. Differences are relative to it (°C for temperatures, % otherwise). Use \"Make baseline\" on another column to change it; drag column headers to reorder." },
                    { "BenchmarkCompareHint",   "Tick runs in the list above with at least two different labels to compare them. Runs with the same label are averaged." },
                    { "CmpCpuTempSteady",       "CPU temp steady (°C)" },
                    { "CmpGpuTempSteady",       "GPU temp steady (°C)" },
                    { "BenchmarkMetricChart",   "TEMPERATURE & MORE" },
                    { "BenchmarkNotSignificantTip", "Smaller than the run-to-run variation; not significant." },
                    { "BenchmarkSignificanceNote", "Every group has 2+ runs: differences smaller than the run-to-run variation are shown grey with \"~\"." },
                    { "BenchmarkSingleRunNote", "With a single run per setting it cannot be told whether a difference is real; FPS usually varies 2–3% between identical runs. Record 2–3 runs per setting." },
                    { "BenchmarkDurationMismatch", "Run lengths differ a lot: a longer run heats up more, so the temperature comparison may not be fair." },
                    { "HeadlineGpuPower",       "GPU power" },
                    { "HeadlineGpuTemp",        "GPU steady" },
                    { "HeadlineLow1",           "1% low" },
                    { "BenchmarkDragTip",       "Drag onto another column to reorder" },
                    { "BenchmarkMakeBaseline",  "Make baseline" },
                    { "BenchmarkExported",      "Saved ✔" },
                    { "BenchmarkExport",        "Export CSV" },
                    { "BenchmarkCompareSection", "COMPARE" },
                    { "BenchmarkHint",          "The first {0} s are dropped as warm-up. For a fair comparison run the same scene for at least 3–5 minutes." },
                    { "BenchmarkNoRtss",        "RTSS is not running: FPS and frame times will not be recorded, only sensors. Start MSI Afterburner / RivaTuner." },
                    { "BenchmarkReady",         "Ready · start and stop from inside the game with {0}." },
                    { "BenchmarkRecording",     "● Recording · {0} · {1} · {2} FPS" },
                    { "BenchmarkStop",          "Stop recording" },
                    { "BenchmarkStart",         "Start recording" },
                    { "BenchmarkLabelCaption",  "Label for the next run (empty: \"Run N\")" },
                    { "BenchmarkDesc",          "You change the settings (e.g. in Afterburner); Warden measures and compares. FPS and frame times come from RTSS (installed with MSI Afterburner); temperature, power and clocks from hardware monitoring." },
                    { "BenchmarkHeader",        "Benchmark" },
                    { "NavShortBenchmark",      "Benchmark" },
                    { "LowDiskSpace",           "Game drive {0} is almost full: {1} free ({2}%)" },
                    { "DriveSpaceLow",          "{0} is almost full · {1} free of {2} ({3}%)" },
                    { "DriveSpace",             "{0} · {1} free of {2} ({3}%)" },
                    { "DaysAgo",                "{0} days ago" },
                    { "Today",                  "Today" },
                    { "LastPlayedUnknown",      "Unknown" },
                    { "NeverPlayed",            "Never played" },
                    { "HistoryColDrive",        "DRIVE" },
                    { "HistoryColSize",         "SIZE" },
                    { "HistoryDiskDesc",        "Installed games, largest first. Games not played for 60 days (or never opened on Steam) are highlighted. Last played comes from Steam or, for other stores, from Warden's history." },
                    { "HistoryDiskSection",     "DISK SPACE" },
                    { "HistoryGamesSection",    "GAMES" },
                    { "HistoryEmpty",           "No sessions yet. When a game with a rule is closed after at least a minute, it shows up here." },
                    { "HistoryDesc",            "Sessions of games with a rule. Sessions under a minute are not saved; temperatures need hardware monitoring, which keeps running while a game is open. The first minute of a game (loading) is left out of the temperatures." },
                    { "HistoryHeader",          "Game History" },
                    { "NavShortHistory",        "History" },
                    { "WarningSelectProcess",   "Please select or enter an executable name." },
                    { "WarningSelectPreset",    "Please select a target EQ preset." },

                    // Page 2: Audio Device Manager
                    { "DeviceManagerHeader",    "Audio Device Manager" },
                    { "DeviceManagerDesc",      "Checked audio devices will be automatically hidden and disabled in the background." },
                    { "DeviceDelayTitle",       "Initial Delay (Seconds):" },
                    { "DeviceDelayDesc",        "Wait time after system startup before enforcing disabled devices." },
                    { "BtnSaveAndApply",        "Apply and Save" },

                    // Page 3: GPU Monitor & Auto Profile
                    { "GpuMonitorHeader",       "GPU Monitor & Auto Profile" },
                    { "GpuMonitorDesc",         "Monitors the graphics card clock (NVIDIA, AMD or Intel) and triggers an Afterburner profile when the limit is exceeded." },
                    { "GpuCoreClock",           "CORE CLOCK" },
                    { "GpuTemperature",         "TEMPERATURE" },
                    { "GpuUsage",               "USAGE" },
                    { "GpuSettingsHeader",      "MSI AFTERBURNER TRIGGER" },
                    { "GpuLimitTitle",          "Maximum Clock Limit (MHz)" },
                    { "GpuLimitDesc",           "If core clock exceeds this threshold, the target profile is automatically applied." },
                    { "GpuProfileTitle",        "Target Profile Number" },
                    { "GpuProfileDesc",         "MSI Afterburner profile slot to apply (1-5)" },
                    { "GpuCooldownTitle",       "Cooldown (Seconds)" },
                    { "GpuCooldownDesc",        "Minimum cooldown period before re-applying the profile." },

                    // Page 4: Telemetry
                    { "TelemetryHeader",        "Hardware Telemetry" },
                    { "TelemetryDesc",          "Real-time temperatures, clock speeds, wattage and utilization metrics." },
                    { "FavoritesTitle",         "FAVORITES / PINNED METRICS" },
                    { "LiveGraphTitle",         "LIVE SENSOR GRAPH (LAST 60 SECONDS)" },
                    { "NoGraphSensorsHint",     "Click 📈 next to any sensor to plot it on the live graph." },
                    { "GraphNow",               "Now" },
                    { "CategoryCpu",            "Processor (CPU)" },
                    { "CategoryGpu",            "Graphics Card (GPU)" },
                    { "CategoryFans",           "Fans & Cooling" },
                    { "CategoryMotherboard",    "Motherboard & System" },
                    { "CategoryMemory",         "Memory (RAM)" },
                    { "PinToFavorites",         "Pin to Favorites" },
                    { "UnpinFromFavorites",     "Unpin from Favorites" },
                    { "PlotOnGraph",            "Plot on Graph" },
                    { "RemoveFromGraph",        "Remove from Graph" },

                    // Tray Context Menu
                    { "TrayOpenSettings",       "Open Dashboard" },
                    { "TrayReloadConfig",       "Reload Configuration" },
                    { "TrayDiscoverPresets",    "Discover Presets" },
                    { "TrayExit",               "Exit" },

                    // Notifications & telemetry sensor names
                    { "Scanning", "Scanning..." },
                    { "ProfileN", "Profile {0}" },
                    { "SecondsN", "{0} Seconds" },
                    { "PresetSwitched", "Preset switched: {0} → {1}" },
                    { "GpuProfileApplied", "Core clock reached {0} MHz. Profile {1} applied." },
                    { "ConnLost", "SteelSeries GG connection lost. Trying to reconnect..." },
                    { "ConnRestored", "SteelSeries GG connection restored." },
                    { "ConfigCorrupt", "config.json could not be read. A backup was saved and default settings were loaded." },
                    { "SensorGpuTemp", "GPU Temperature" },
                    { "SensorGpuHotSpot", "GPU Hot Spot Temperature" },
                    { "SensorGpuPower", "GPU Power (Watt)" },
                    { "SensorGpuCoreClock", "GPU Core Clock (MHz)" },
                    { "SensorGpuMemClock", "GPU Memory Clock (MHz)" },
                    { "SensorGpuLoad", "GPU Usage (%)" },
                    { "SensorCpuTemp", "CPU Package Temperature" },
                    { "SensorCpuPower", "CPU Power (Watt)" },
                    { "SensorCpuClock", "CPU Clock (MHz)" },
                    { "SensorCpuLoad", "CPU Total Usage (%)" },
                    { "SensorSystemTemp", "System Temperature" },
                    { "SensorChipset", "Chipset" },
                    { "SensorVrm", "VRM MOS Temperature" },
                    { "SensorMemLoad", "Memory Usage (%)" },
                    { "SensorMemUsed", "Used Memory" }
                }
            },
            {
                "TR", new Dictionary<string, string>
                {
                    // General / Shell
                    { "Title",                  "Warden" },
                    { "Online",                 "ÇEVRİMİÇİ" },
                    { "Settings",               "Ayarlar" },
                    { "SettingsHeader",         "Ayarlar" },
                    { "SettingsDesc",           "Yalnızca kullandığınız özellikleri açın. Değişiklikler hemen uygulanır." },
                    { "GoToDevicesPage",        "Ses sayfasını aç →" },
                    { "DeviceSettingsHint",     "Devre dışı tutulacak cihazlar Ses sayfasından seçilir." },
                    { "GoToGpuPage",            "GPU sayfasını aç →" },
                    { "GpuSettingsHint",        "Saat hızı sınırı ve Afterburner profili GPU sayfasından ayarlanır." },
                    { "IntervalSeconds",        "{0} sn'de bir" },
                    { "AutoSaveHint",           "Değişiklikler otomatik kaydedilir ✓" },
                    { "GeneralSection",         "GENEL" },
                    { "StartWithWin",           "Windows ile Başlat" },
                    { "StartWithWinDesc",       "Bilgisayar açıldığında arka planda sistem tepsisinde sessizce başlar." },
                    { "StartupInsecureTitle",   "Windows ile başlatma kapatıldı" },
                    { "NavOverview",             "Panel" },
                    { "NavShortOverview",        "Panel" },
                    { "NavShortSonar",           "Sonar" },
                    { "NavShortAudio",           "Ses" },
                    { "NavShortGpu",             "GPU" },
                    { "NavShortSensors",         "Sensörler" },
                    { "NavShortStatus",          "Durum" },
                    { "NavShortSettings",        "Ayarlar" },
                    { "OvTitle",                 "Panel" },
                    { "OvDesc",                  "Oyun ve sistem durumu tek ekranda" },
                    { "OvScan",                  "Oyunları tara" },
                    { "OvRecordStart",           "● KAYIT" },
                    { "OvRecordStop",            "■ DURDUR" },
                    { "OvInGame",                "OYUNDA" },
                    { "OvDesktop",               "MASAÜSTÜ" },
                    { "OvDesktopHint",           "Kuralı olan bir oyun açıldığında burada görünür" },
                    { "OvSession",               "oturum süresi" },
                    { "OvLoad",                  "Yük {0}" },
                    { "OvClock",                 "Saat {0}" },
                    { "OvPower",                 "Güç {0}" },
                    { "OvGraph",                 "SON 60 SANİYE · SICAKLIK" },
                    { "OvTileRam",               "Bellek" },
                    { "OvTileHotSpot",           "GPU hot spot" },
                    { "OvTileFan",               "En hızlı fan" },
                    { "OvTileCpuPower",          "CPU gücü" },
                    { "OvChipRecord",            "Kayıt" },
                    { "OvChipUpdate",            "Sürüm" },
                    { "OvConnected",             "BAĞLI" },
                    { "OvDisconnected",          "YOK" },
                    { "OvReady",                 "HAZIR" },
                    { "OvMissing",               "EKSİK" },
                    { "OvOff",                   "KAPALI" },
                    { "OvRecording",             "KAYITTA" },
                    { "OvIdle",                  "BEKLEMEDE" },
                    { "OvUpdateAvailable",       "{0} ÇIKTI" },
                    { "SonarConnectedAt",        "Sonar bağlı: {0}" },
                    { "SonarWidgetHint",         "Ayrıntılar için tıkla" },
                    { "NavStatus",               "Sistem Durumu" },
                    { "GpuNotFound",             "GPU sensörü bulunamadı" },
                    { "GpuDetecting",            "Ekran kartı algılanıyor..." },
                    { "TempAlarm",               "⚠ {0} sıcaklığı {1}°C (sınır {2}°C)" },
                    { "TempAlarmTitle",          "Sıcaklık alarmı" },
                    { "TempAlarmDesc",           "Sıcaklık 10 saniye boyunca sınırın üstünde kalırsa bildirim gönderir (en fazla 10 dakikada bir)." },
                    { "CpuTempLimit",            "CPU sınırı (°C)" },
                    { "GpuTempLimit",            "GPU sınırı (°C)" },
                    { "RecordAuto",              "Kuralı olan bir oyun açıkken otomatik kaydet" },
                    { "RecordOpenFolder",        "📁 Kayıtlar" },
                    { "RecordStart",             "⏺ Kaydı başlat" },
                    { "RecordStop",              "⏹ Durdur" },
                    { "RecordIdle",              "Kayıt yok" },
                    { "RecordActive",            "Kaydediliyor: {0} ({1}) → {2}" },
                    { "RecordKindAuto",          "otomatik" },
                    { "RecordKindManual",        "elle" },
                    { "RecordManualLabel",       "elle" },
                    { "StatusHeader",            "Sistem Durumu" },
                    { "StatusDesc",              "Warden'ın ihtiyaç duyduğu programlar ve sürücüler. Gereksinimi eksik olan özellikler çalışmaz." },
                    { "StatusRecheck",           "Yeniden kontrol et" },
                    { "StatusChecking",          "Kontrol ediliyor..." },
                    { "StatusDownload",          "İndir" },
                    { "StatusAdmin",             "Yönetici yetkisi" },
                    { "StatusAdminOk",           "Warden yönetici olarak çalışıyor (sensörler ve ses cihazları için gerekli)." },
                    { "StatusAdminMissing",      "Yönetici değil: sensörler ve ses cihazı kontrolü çalışmaz." },
                    { "StatusInstall",           "Kurulum konumu" },
                    { "StatusInstallOk",         "Korumalı klasör: {0}. \"Windows ile başlat\" kullanılabilir." },
                    { "StatusInstallInsecure",   "Klasör standart kullanıcılar tarafından değiştirilebiliyor, bu yüzden \"Windows ile başlat\" kapalı kalır. Setup ile kur. ({0})" },
                    { "StatusGgOk",              "Kurulu." },
                    { "StatusGgMissing",         "Kurulu değil: otomatik Sonar EQ değişimi çalışmaz." },
                    { "StatusSonarOk",           "Çalışıyor: {0}." },
                    { "StatusSonarMissing",      "Ulaşılamıyor: SteelSeries GG'yi aç ve Sonar'ın etkin olduğundan emin ol." },
                    { "StatusAfterburnerMissing", "Bulunamadı: otomatik GPU profili çalışmaz." },
                    { "StatusPawnIoOk",          "Kurulu: CPU sensörleri okunabiliyor." },
                    { "StatusPawnIoMissing",     "Kurulu değil: CPU sıcaklık, saat ve güç boş kalabilir (winget install namazso.PawnIO)." },
                    { "StatusGpu",               "Ekran kartı" },
                    { "StatusGpuMissing",        "GPU sensörü bulunamadı. GPU sayfası ve GPU sıcaklık alarmı boş kalır." },
                    { "StatusUpdate",            "Güncellemeler" },
                    { "UpdatesSection",          "GÜNCELLEMELER" },
                    { "UpdateAutoCheck",         "Güncellemeleri otomatik kontrol et" },
                    { "UpdateAutoCheckDesc",     "Açılışta ve 6 saatte bir GitHub'daki sürümlere bakar." },
                    { "UpdateCurrentVersion",    "Yüklü sürüm: {0}" },
                    { "BtnCheckUpdates",         "Şimdi kontrol et" },
                    { "BtnInstallUpdate",        "{0} sürümünü kur" },
                    { "UpdateChecking",          "Güncellemeler kontrol ediliyor..." },
                    { "UpdateUpToDate",          "En güncel sürümü kullanıyorsun." },
                    { "UpdateAvailable",         "Yeni sürüm var: {0}" },
                    { "UpdateUnavailable",       "Sürüm bilgisi alınamadı (repo gizli olabilir)." },
                    { "UpdateError",             "Güncelleme kontrolü başarısız: {0}" },
                    { "UpdateDownloading",       "İndiriliyor... %{0}" },
                    { "UpdateInstalling",        "Kuruluyor, Warden birkaç saniye içinde yeniden açılacak..." },
                    { "UpdateFailed",            "Güncelleme başarısız: {0}" },
                    { "UpdateHashMismatch",      "indirilen dosya doğrulanamadı (SHA256 uyuşmuyor). Hiçbir şey kurulmadı." },
                    { "UpdateCancelled",         "Güncelleme tamamlanmadı; Warden çalışmaya devam ediyor." },
                    { "UpdateBalloon",           "Warden {0} çıktı. Kurmak için tıkla." },
                    { "UpdateConfirm",           "Warden {0} şimdi kurulsun mu?\n\nWarden kapanıp birkaç saniye içinde yeniden açılacak. Ayarların korunur." },
                    { "UpdateConfirmTitle",      "Warden güncellemesi" },
                    { "TrayInstallUpdate",       "Güncellemeyi kur ({0})" },
                    { "RuleExists",             "{0} için zaten bir kural var. O kuralın preset'ini değiştir." },
                    { "PawnIoMissing",          "PawnIO sürücüsü kurulu değil; CPU sıcaklık, saat ve güç sensörleri boş kalabilir. \"winget install namazso.PawnIO\" ile ya da şuradan kurabilirsin:" },
                    { "StartupInsecureBody",    "Warden oturum açılışında yönetici yetkisiyle başlıyor, ancak klasörü standart kullanıcılar tarafından değiştirilebiliyor:\n\n{0}\n\nSenin yetkinle çalışan herhangi bir program Warden.exe'yi veya bir DLL'ini değiştirip sonraki açılışta yönetici yetkisi kazanabilir. Bu yüzden \"Windows ile başlat\" kapatıldı.\n\nAçmak için Warden'ı korumalı bir klasöre (ör. C:\\Program Files\\Warden) yönetici terminalinden yayınla:\ndotnet publish -c Release -o \"C:\\Program Files\\Warden\"\n\nAyrıntı: {1}" },
                    { "Language",               "Dil / Language" },
                    { "ScanInterval",           "Oyun kontrol sıklığı" },
                    { "ScanIntervalDesc",       "Öndeki oyunun ne sıklıkla kontrol edileceği. Kısa süre daha hızlı geçiş, uzun süre daha az işlemci kullanımı demektir." },
                    { "BtnSave",                "Kaydet" },
                    { "SaveSuccess",            "Ayarlar başarıyla kaydedildi!" },
                    { "SavedSuccess",           "Kaydedildi ✔" },
                    { "Connecting",             "Bağlanıyor..." },
                    { "Connected",              "Bağlandı" },
                    { "ConnFailed",             "Bağlantı Başarısız" },
                    { "Active",                 "Aktif" },
                    { "Desktop",                "Masaüstü" },
                    { "Info",                   "Bilgi" },
                    { "Warning",                "Uyarı" },
                    { "Error",                  "Hata" },

                    // Window Chrome Tooltips
                    { "ToolTipMinimize",        "Simge Durumuna Küçült" },
                    { "ToolTipMaximize",        "Ekranı Kapla" },
                    { "ToolTipClose",           "Kapat (Arka planda sistem tepsisinde çalışır)" },

                    // Navigation Tooltips
                    { "NavHome",                "Sonar Profilleri" },
                    { "NavDeviceManager",       "Ses Aygıtı Yöneticisi" },
                    { "NavGpuMonitor",          "GPU Performans & Monitör" },
                    { "NavTelemetry",           "Donanım Sensörleri & Telemetri" },
                    { "NavSettings",            "Ayarlar" },

                    // Page 1: Sonar Profiles & Rules
                    { "RulesHeader",            "Otomatik Geçiş Profilleri" },
                    { "RulesDesc",              "Aktif oyun ve uygulamalara göre SteelSeries Sonar profillerini otomatik değiştirir." },
                    { "DefaultEQ",              "Varsayılan Profil:" },
                    { "DefaultEQDesc",          "Hiçbir kural eşleşmediğinde veya masaüstündeyken kullanılır." },
                    { "PerAppConfig",           "UYGULAMA / OYUN" },
                    { "TargetSonarConfig",      "HEDEF SONAR PROFİLİ" },
                    { "BtnScan",                "Yüklü Oyunları Tara" },
                    { "BtnClear",               "Sıfırla" },
                    { "ClearScannedGames",      "Taranmış Oyunları Temizle" },
                    { "ClearScannedGamesDesc",  "Arka planda keşfedilen tüm exe isimlerini sıfırlar." },
                    { "ClearedSuccess",         "Taranmış oyun listesi başarıyla sıfırlandı." },
                    { "ClearedSuccessTitle",    "Sıfırlandı" },
                    { "ManualAdd",              "Manuel Ekle:" },
                    { "ManualAddDesc",          "Eğer taramada bulunamadıysa oyunun EXE adını elle ekleyin." },
                    { "ManualExe",              "EXE Adı" },
                    { "ManualName",             "Görünür Ad (İsteğe Bağlı)" },
                    { "ManualBrowse",           "Gözat" },
                    { "BtnAddManual",           "Ekle" },
                    { "BtnAddRule",             "Oyun Ekle" },
                    { "BtnDeleteRule",          "Kaldır" },
                    { "ManualSuccess",          "Oyun başarıyla eklendi!" },
                    { "ScanDone",               "{0} yeni oyun bulundu" },
                    { "ScanNone",               "Yeni oyun bulunamadı" },
                    { "ScanMatched",            "{0} GG profili atandı" },
                    { "ScanRemoved",            "{0} kaldırılmış oyun silindi" },
                    { "ScanBusy",               "Tarama zaten sürüyor" },
                    { "AutoScanAdded",          "Yeni oyunlar: {0}" },
                    { "AutoScanAssigned",       "GG profili atandı: {0}" },
                    { "AutoScanRemoved",        "Kaldırılan: {0}" },
                    { "AutoScan",               "Açılışta yüklü oyunları tara" },
                    { "AutoScanDesc",           "Yeni ve kaldırılan oyunları bulur, değişiklik varsa bildirim gösterir." },
                    { "AutoAssign",             "GG oyun profillerini otomatik ata" },
                    { "AutoAssignDesc",         "SteelSeries GG'de oyuna özel profili olan oyunlara o profili atar. Var olan kurallara dokunmaz." },
                    { "ModulesSection",         "MODÜLLER" },
                    { "ModuleSonar",            "Sonar profil geçişi" },
                    { "ModuleSonarDesc",        "Bir oyun öne geldiğinde SteelSeries Sonar ses profilini o oyun için seçilen profile geçirir, oyun kapanınca varsayılan profile döner. Kapalıyken Warden SteelSeries GG ile hiç iletişim kurmaz; oyun takibi (Panel, otomatik kayıt) çalışmaya devam eder." },
                    { "ModuleAudioDevices",     "Ses cihazı denetleyicisi" },
                    { "ModuleAudioDevicesDesc", "Seçilen ses cihazlarını (ör. kullanılmayan sanal veya hayalet cihazlar) devre dışı tutar. Windows ya da GG onları yeniden açarsa 30 saniye içinde tekrar kapatır." },
                    { "ModuleHardware",         "Donanım izleme" },
                    { "ModuleHardwareDesc",     "CPU ve GPU sıcaklığını, saat hızını, gücünü ve fanları okur. Sensörler sayfası, Panel göstergeleri, sıcaklık alarmı ve CSV kaydı bu modülü kullanır. Kapalıyken sensör sürücüsü hiç yüklenmez; bir oyunun anti-cheat sistemiyle sorun yaşanırsa kapatılabilir." },
                    { "ModuleGpuProfile",       "GPU / Afterburner profili" },
                    { "ModuleGpuProfileDesc",   "GPU saat hızı belirlenen sınırı aşınca MSI Afterburner'da seçilen profili uygular (ör. güç sınırlı bir profil). Saat hızını sensörlerden okuduğu için donanım izleme açık olmalıdır." },
                    { "ModuleOffTitle",         "Bu modül kapalı" },
                    { "ModuleOffDesc",          "Arka planda çalışmıyor. Bu sayfayı kullanmak için modülü açın." },
                    { "ModuleGpuNeedsHardware", "GPU profili saat hızını sensörlerden okur; açınca donanım izleme de açılır." },
                    { "ModuleEnable",           "Modülü aç" },
                    { "SonarModuleOff",         "Sonar modülü kapalı" },
                    { "StatusModuleOff",        "Modül kapalı" },
                    { "SessionSummaryTitle",    "{0} · {1}" },
                    { "SessionSummaryMaxTemp",  "{0} en yüksek {1} °C" },
                    { "DurationHoursMinutes",   "{0} sa {1} dk" },
                    { "DurationMinutes",        "{0} dk" },
                    { "SessionSummary",         "Oyun kapanınca özet göster" },
                    { "SessionSummaryDesc",     "Oynama süresi ve en yüksek CPU ile GPU sıcaklığını bildirim olarak gösterir." },
                    { "HistoryColGpuMax",       "GPU MAKS" },
                    { "HistoryColCpuMax",       "CPU MAKS" },
                    { "HistoryColDuration",     "SÜRE" },
                    { "HistoryColDate",         "TARİH" },
                    { "HistoryColGpu",          "GPU ORT / MAKS" },
                    { "HistoryColCpu",          "CPU ORT / MAKS" },
                    { "HistoryColLastPlayed",   "SON OYNAMA" },
                    { "HistoryColSessions",     "OTURUM" },
                    { "HistoryColTotal",        "TOPLAM" },
                    { "HistoryColGame",         "OYUN" },
                    { "HistorySessionsSection", "SON OTURUMLAR" },
                    { "Seconds",                "{0} sn" },
                    { "BenchmarkWarmupDesc",    "Her kaydın başından atılan süre (yükleme, shader derleme, boost'a çıkış)." },
                    { "BenchmarkWarmup",        "Isınma süresi" },
                    { "BenchmarkHotkeyTaken",   "{0} başka bir uygulama tarafından kullanılıyor; başka bir tuş seçin." },
                    { "BenchmarkHotkeyDesc",    "Oyunun içinden kaydı başlatır / durdurur." },
                    { "BenchmarkHotkey",        "Kayıt kısayolu" },
                    { "ModuleBenchmarkDesc",    "Ayarları (ör. Afterburner profilleri) siz değiştirirsiniz; Warden saniyede bir FPS, kare süresi, sıcaklık, watt ve frekansı kaydeder; ortalama FPS, %1 low ve watt başına FPS hesaplar. FPS için RTSS (Afterburner ile gelir) açık olmalı. Kapalıyken kısayol tuşu kaydedilmez." },
                    { "ModuleBenchmark",        "Benchmark / Karşılaştırma" },
                    { "BenchmarkTooShort",      "Kayıt ısınma süresinden kısa, özet eksik." },
                    { "BenchmarkStoppedFps",    "Ort. {0} FPS · %1 low {1}" },
                    { "BenchmarkStopped",       "Benchmark kaydı durdu: {0} · {1}" },
                    { "BenchmarkStarted",       "Benchmark kaydı başladı: {0}\nDurdurmak için {1}" },
                    { "BenchmarkAutoLabel",     "Kayıt {0}" },
                    { "BenchmarkDeleteConfirm", "\"{0}\" kaydı silinsin mi?" },
                    { "BenchmarkDelete",        "Kaydı sil" },
                    { "BenchmarkRenameTip",     "Yeniden adlandırmak için tıklayın" },
                    { "BenchmarkRunShort",      "Isınma süresinden kısa; özet yok." },
                    { "BenchmarkRunEfficiency", "{0} FPS/W ({1})" },
                    { "BenchmarkRunDevice",     "{0} ort. {1} MHz ({2}–{3}) · {4} / {5} °C (ort / p95) · {6} W · %{7} yük" },
                    { "BenchmarkRunFps",        "Ort. {0} FPS · %1 low {1}" },
                    { "BenchmarkNoRuns",        "Henüz kayıt yok." },
                    { "EffTotal",               "Toplam" },
                    { "EffCpu",                 "CPU" },
                    { "EffGpu",                 "GPU" },
                    { "BenchmarkEfficiency",    "Watt başına FPS:" },
                    { "BenchmarkRunsSection",   "KAYITLAR" },
                    { "ChartCpuClock",          "CPU frekansı" },
                    { "ChartGpuClock",          "GPU frekansı" },
                    { "ChartTotalPower",        "Toplam güç" },
                    { "ChartCpuPower",          "CPU gücü" },
                    { "ChartGpuPower",          "GPU gücü" },
                    { "ChartCpuTemp",           "CPU sıcaklığı" },
                    { "ChartGpuTemp",           "GPU sıcaklığı" },
                    { "ChartFps",               "FPS" },
                    { "CmpCpuLoad",             "CPU yükü (%)" },
                    { "CmpGpuLoad",             "GPU yükü (%)" },
                    { "CmpTotalPower",          "Toplam güç (W)" },
                    { "CmpCpuPower",            "CPU gücü (W)" },
                    { "CmpGpuPower",            "GPU gücü (W)" },
                    { "CmpCpuTempP95",          "CPU sıcaklığı p95 (°C)" },
                    { "CmpCpuTemp",             "CPU sıcaklığı ort. (°C)" },
                    { "CmpGpuTempP95",          "GPU sıcaklığı p95 (°C)" },
                    { "CmpGpuTemp",             "GPU sıcaklığı ort. (°C)" },
                    { "CmpCpuClock",            "CPU frekansı ort. (MHz)" },
                    { "CmpCpuClockMin",         "CPU frekansı en düşük (MHz)" },
                    { "CmpCpuClockMax",         "CPU frekansı en yüksek (MHz)" },
                    { "CmpGpuClock",            "GPU frekansı ort. (MHz)" },
                    { "CmpGpuClockMin",         "GPU frekansı en düşük (MHz)" },
                    { "CmpGpuClockMax",         "GPU frekansı en yüksek (MHz)" },
                    { "CmpFpsPerWatt",          "Watt başına FPS ({0})" },
                    { "CmpLow1Fps",             "%1 low FPS" },
                    { "CmpAvgFps",              "Ortalama FPS" },
                    { "CmpMetric",              "Ölçü" },
                    { "CsvSamplesSuffix",       "-saniyelik" },
                    { "BenchmarkChartNoData",   "Bu ölçü için veri yok." },
                    { "BenchmarkBaseline",      "temel" },
                    { "BenchmarkRunsCount",     "{0} kayıt" },
                    { "BenchmarkSelectTip",     "Karşılaştırmaya ekle" },
                    { "BenchmarkCompareMax",    "En fazla {0} grup karşılaştırılır; fazlası gösterilmez." },
                    { "BenchmarkCompareBaseline", "Temel: {0}. Farklar ona göre (sıcaklıkta °C, diğerlerinde %). Başka bir sütunda \"Temel yap\" ile değiştirin; sütun başlıklarını sürükleyerek sırayı değiştirin." },
                    { "BenchmarkCompareHint",   "Karşılaştırmak için yukarıdaki listeden en az iki farklı etikete ait kaydı işaretleyin. Aynı etiketli kayıtların ortalaması alınır." },
                    { "CmpCpuTempSteady",       "CPU sıcaklığı kararlı (°C)" },
                    { "CmpGpuTempSteady",       "GPU sıcaklığı kararlı (°C)" },
                    { "BenchmarkMetricChart",   "SICAKLIK VE DİĞER ÖLÇÜLER" },
                    { "BenchmarkNotSignificantTip", "Kayıtlar arası dalgalanmadan küçük; anlamlı değil." },
                    { "BenchmarkSignificanceNote", "Her grupta 2+ kayıt var: kayıtlar arası dalgalanmadan küçük farklar gri ve \"~\" ile gösterilir." },
                    { "BenchmarkSingleRunNote", "Ayar başına tek kayıtla farkın gerçek olup olmadığı anlaşılamaz; aynı ayarla yapılan iki test arasında bile FPS genelde %2–3 oynar. Her ayarla 2–3 kayıt alın." },
                    { "BenchmarkDurationMismatch", "Kayıt süreleri birbirinden çok farklı: uzun test daha çok ısınır, sıcaklık karşılaştırması adil olmayabilir." },
                    { "HeadlineGpuPower",       "GPU gücü" },
                    { "HeadlineGpuTemp",        "GPU kararlı" },
                    { "HeadlineLow1",           "%1 low" },
                    { "BenchmarkDragTip",       "Başka bir sütunun üstüne sürükleyip bırakarak sırayı değiştirin" },
                    { "BenchmarkMakeBaseline",  "Temel yap" },
                    { "BenchmarkExported",      "Kaydedildi ✔" },
                    { "BenchmarkExport",        "CSV dışa aktar" },
                    { "BenchmarkCompareSection", "KARŞILAŞTIRMA" },
                    { "BenchmarkHint",          "İlk {0} sn ısınma olarak atılır. Adil bir karşılaştırma için aynı sahneyi en az 3–5 dakika test edin." },
                    { "BenchmarkNoRtss",        "RTSS çalışmıyor: FPS ve kare süresi kaydedilmez, yalnızca sensörler kaydedilir. MSI Afterburner / RivaTuner'ı açın." },
                    { "BenchmarkReady",         "Hazır · oyunun içinden {0} ile başlatıp durdurabilirsiniz." },
                    { "BenchmarkRecording",     "● Kaydediliyor · {0} · {1} · {2} FPS" },
                    { "BenchmarkStop",          "Kaydı durdur" },
                    { "BenchmarkStart",         "Kaydı başlat" },
                    { "BenchmarkLabelCaption",  "Sonraki kaydın etiketi (boşsa \"Kayıt N\")" },
                    { "BenchmarkDesc",          "Ayarları siz değiştirirsiniz (ör. Afterburner'da); Warden ölçer ve karşılaştırır. FPS ve kare süresi RTSS'ten (MSI Afterburner ile gelir), sıcaklık, watt ve frekans donanım izlemeden okunur." },
                    { "BenchmarkHeader",        "Benchmark" },
                    { "NavShortBenchmark",      "Benchmark" },
                    { "LowDiskSpace",           "{0} oyun diski dolmak üzere: {1} boş (%{2})" },
                    { "DriveSpaceLow",          "{0} dolmak üzere · {1} boş / {2} (%{3})" },
                    { "DriveSpace",             "{0} · {1} boş / {2} (%{3})" },
                    { "DaysAgo",                "{0} gün önce" },
                    { "Today",                  "Bugün" },
                    { "LastPlayedUnknown",      "Bilinmiyor" },
                    { "NeverPlayed",            "Hiç oynanmadı" },
                    { "HistoryColDrive",        "SÜRÜCÜ" },
                    { "HistoryColSize",         "BOYUT" },
                    { "HistoryDiskDesc",        "Kurulu oyunlar, en büyük önce. 60 gündür oynanmayan (veya Steam'de hiç açılmamış) oyunlar renkli gösterilir. Son oynama Steam'den, diğer mağazalar için Warden geçmişinden alınır." },
                    { "HistoryDiskSection",     "DİSK ALANI" },
                    { "HistoryGamesSection",    "OYUNLAR" },
                    { "HistoryEmpty",           "Henüz oturum yok. Kuralı olan bir oyun en az 1 dakika oynanıp kapatılınca burada görünür." },
                    { "HistoryDesc",            "Kuralı olan oyunların oturumları. 1 dakikadan kısa oturumlar kaydedilmez; sıcaklıklar için donanım izleme açık olmalı, oyun açıkken sensörler çalışmaya devam eder. Oyunun ilk dakikası (yükleme) sıcaklıklara sayılmaz." },
                    { "HistoryHeader",          "Oyun Geçmişi" },
                    { "NavShortHistory",        "Geçmiş" },
                    { "WarningSelectProcess",   "Lütfen bir işlem adı seçin veya yazın." },
                    { "WarningSelectPreset",    "Lütfen bir hedef EQ profili seçin." },

                    // Page 2: Audio Device Manager
                    { "DeviceManagerHeader",    "Ses Cihazı Yöneticisi" },
                    { "DeviceManagerDesc",      "İşaretlenen ses cihazları arka planda otomatik olarak gizlenir ve devre dışı bırakılır." },
                    { "DeviceDelayTitle",       "İlk Gecikme (Saniye):" },
                    { "DeviceDelayDesc",        "Sistem açıldıktan sonra cihazların devre dışı bırakılması için bekleme süresi." },
                    { "BtnSaveAndApply",        "Uygula ve Kaydet" },

                    // Page 3: GPU Monitor & Auto Profile
                    { "GpuMonitorHeader",       "GPU Monitör & Otomatik Profil" },
                    { "GpuMonitorDesc",         "Ekran kartı frekansını (NVIDIA, AMD veya Intel) izler ve limit aşıldığında Afterburner profilini tetikler." },
                    { "GpuCoreClock",           "ÇEKİRDEK HIZI" },
                    { "GpuTemperature",         "SICAKLIK" },
                    { "GpuUsage",               "KULLANIM" },
                    { "GpuSettingsHeader",      "MSI AFTERBURNER TETİKLEYİCİ" },
                    { "GpuLimitTitle",          "Maksimum Saat Hızı Sınırı (MHz)" },
                    { "GpuLimitDesc",           "Çekirdek hızı bu sınırı aşarsa hedef profil otomatik olarak uygulanır." },
                    { "GpuProfileTitle",        "Hedef Profil Numarası" },
                    { "GpuProfileDesc",         "Uygulanacak MSI Afterburner profil slotu (1-5)" },
                    { "GpuCooldownTitle",       "Bekleme Süresi (Saniye)" },
                    { "GpuCooldownDesc",        "Profil tekrar uygulanmadan önceki bekleme süresi." },

                    // Page 4: Telemetry
                    { "TelemetryHeader",        "Sistem Telemetrisi" },
                    { "TelemetryDesc",          "Canlı sıcaklıklar, saat hızları, güç tüketimleri ve kullanım oranları." },
                    { "FavoritesTitle",         "FAVORİLER / HIZLI BAKIŞ" },
                    { "LiveGraphTitle",         "CANLI SENSÖR GRAFİĞİ (SON 60 SANİYE)" },
                    { "NoGraphSensorsHint",     "Grafikte çizilmesini istediğiniz değerlerin yanındaki 📈 butonuna tıklayın." },
                    { "GraphNow",               "Şimdi" },
                    { "CategoryCpu",            "İşlemci (CPU)" },
                    { "CategoryGpu",            "Ekran Kartı (GPU)" },
                    { "CategoryFans",           "Fanlar & Soğutma" },
                    { "CategoryMotherboard",    "Anakart & Sistem" },
                    { "CategoryMemory",         "Bellek (RAM)" },
                    { "PinToFavorites",         "Favorilere Ekle" },
                    { "UnpinFromFavorites",     "Favorilerden Kaldır" },
                    { "PlotOnGraph",            "Grafiğe Ekle" },
                    { "RemoveFromGraph",        "Grafikten Kaldır" },

                    // Tray Context Menu
                    { "TrayOpenSettings",       "Kontrol Panelini Aç" },
                    { "TrayReloadConfig",       "Yapılandırmayı Yenile" },
                    { "TrayDiscoverPresets",    "Profilleri Keşfet" },
                    { "TrayExit",               "Çıkış" },

                    // Notifications & telemetry sensor names
                    { "Scanning", "Taranıyor..." },
                    { "ProfileN", "Profil {0}" },
                    { "SecondsN", "{0} Saniye" },
                    { "PresetSwitched", "Profil değişti: {0} → {1}" },
                    { "GpuProfileApplied", "Çekirdek hızı {0} MHz'e ulaştı. Profil {1} uygulandı." },
                    { "ConnLost", "SteelSeries GG bağlantısı kesildi. Yeniden bağlanmaya çalışıyor..." },
                    { "ConnRestored", "SteelSeries GG bağlantısı yeniden kuruldu." },
                    { "ConfigCorrupt", "config.json okunamadı. Yedeği alındı ve varsayılan ayarlar yüklendi." },
                    { "SensorGpuTemp", "GPU Sıcaklığı" },
                    { "SensorGpuHotSpot", "GPU Hot Spot Sıcaklığı" },
                    { "SensorGpuPower", "GPU Güç Tüketimi (Watt)" },
                    { "SensorGpuCoreClock", "GPU Çekirdek Hızı (MHz)" },
                    { "SensorGpuMemClock", "GPU Bellek Hızı (MHz)" },
                    { "SensorGpuLoad", "GPU Kullanımı (%)" },
                    { "SensorCpuTemp", "CPU Paket Sıcaklığı" },
                    { "SensorCpuPower", "CPU Güç Tüketimi (Watt)" },
                    { "SensorCpuClock", "CPU Saat Hızı (MHz)" },
                    { "SensorCpuLoad", "CPU Toplam Kullanım (%)" },
                    { "SensorSystemTemp", "Sistem Sıcaklığı" },
                    { "SensorChipset", "Yonga Seti (Chipset)" },
                    { "SensorVrm", "VRM MOS Sıcaklığı" },
                    { "SensorMemLoad", "Bellek Kullanımı (%)" },
                    { "SensorMemUsed", "Kullanılan Bellek" }
                }
            }
        };

        /// <summary>Yerelleştirilmiş metni string.Format ile doldurur.</summary>
        public static string Format(string key, params object[] args)
            => string.Format(Get(key), args);

        /// <summary>"1 sa 42 dk" / "12 dk" (saat 24'ü geçse de saat olarak sayılır).</summary>
        public static string Duration(TimeSpan duration)
        {
            int hours = (int)duration.TotalHours;
            return hours > 0
                ? Format("DurationHoursMinutes", hours, duration.Minutes)
                : Format("DurationMinutes", (int)duration.TotalMinutes);
        }

        public static string Get(string key)
        {
            if (Strings.TryGetValue(CurrentLang, out var langDict) &&
                langDict.TryGetValue(key, out var val))
                return val;

            if (Strings["EN"].TryGetValue(key, out var fallback))
                return fallback;

            return key;
        }
    }
}
